DROP TABLE IF EXISTS chorizon_copy;

CREATE TABLE chorizon_copy
(
  OID_ int,
  hzname text,
  desgndisc smallint,
  desgnmaster text,
  desgnmasterprime text,
  desgnvert smallint,
  hzdept_l smallint,
  hzdept_r smallint,
  hzdept_h smallint,
  hzdepb_l smallint,
  hzdepb_r smallint,
  hzdepb_h smallint,
  hzthk_l smallint,
  hzthk_r smallint,
  hzthk_h smallint,
  fraggt10_l smallint,
  fraggt10_r smallint,
  fraggt10_h smallint,
  frag3to10_l smallint,
  frag3to10_r smallint,
  frag3to10_h smallint,
  sieveno4_l float,
  sieveno4_r float,
  sieveno4_h float,
  sieveno10_l float,
  sieveno10_r float,
  sieveno10_h float,
  sieveno40_l float,
  sieveno40_r float,
  sieveno40_h float,
  sieveno200_l float,
  sieveno200_r float,
  sieveno200_h float,
  sandtotal_l double precision,
  sandtotal_r double precision,
  sandtotal_h double precision,
  sandvc_l double precision,
  sandvc_r double precision,
  sandvc_h double precision,
  sandco_l double precision,
  sandco_r double precision,
  sandco_h double precision,
  sandmed_l double precision,
  sandmed_r double precision,
  sandmed_h double precision,
  sandfine_l double precision,
  sandfine_r double precision,
  sandfine_h double precision,
  sandvf_l double precision,
  sandvf_r double precision,
  sandvf_h double precision,
  silttotal_l double precision,
  silttotal_r double precision,
  silttotal_h double precision,
  siltco_l float,
  siltco_r float,
  siltco_h float,
  siltfine_l float,
  siltfine_r float,
  siltfine_h float,
  claytotal_l float,
  claytotal_r float,
  claytotal_h float,
  claysizedcarb_l float,
  claysizedcarb_r float,
  claysizedcarb_h float,
  om_l float,
  om_r float,
  om_h float,
  dbtenthbar_l text,
  dbtenthbar_r text,
  dbtenthbar_h text,
  dbthirdbar_l double precision,
  dbthirdbar_r double precision,
  dbthirdbar_h double precision,
  dbfifteenbar_l text,
  dbfifteenbar_r text,
  dbfifteenbar_h text,
  dbovendry_l double precision,
  dbovendry_r double precision,
  dbovendry_h double precision,
  partdensity float,
  ksat_l double precision,
  ksat_r double precision,
  ksat_h double precision,
  awc_l float,
  awc_r float,
  awc_h float,
  wtenthbar_l double precision,
  wtenthbar_r double precision,
  wtenthbar_h double precision,
  wthirdbar_l double precision,
  wthirdbar_r double precision,
  wthirdbar_h double precision,
  wfifteenbar_l double precision,
  wfifteenbar_r double precision,
  wfifteenbar_h double precision,
  wsatiated_l smallint,
  wsatiated_r smallint,
  wsatiated_h smallint,
  lep_l double precision,
  lep_r double precision,
  lep_h double precision,
  ll_l float,
  ll_r float,
  ll_h float,
  pi_l float,
  pi_r float,
  pi_h float,
  aashind_l smallint,
  aashind_r smallint,
  aashind_h smallint,
  kwfact float,
  kffact float,
  caco3_l smallint,
  caco3_r smallint,
  caco3_h smallint,
  gypsum_l smallint,
  gypsum_r smallint,
  gypsum_h smallint,
  sar_l float,
  sar_r float,
  sar_h float,
  ec_l float,
  ec_r float,
  ec_h float,
  cec7_l double precision,
  cec7_r double precision,
  cec7_h double precision,
  ecec_l double precision,
  ecec_r double precision,
  ecec_h double precision,
  sumbases_l double precision,
  sumbases_r double precision,
  sumbases_h double precision,
  ph1to1h2o_l double precision,
  ph1to1h2o_r double precision,
  ph1to1h2o_h double precision,
  ph01mcacl2_l double precision,
  ph01mcacl2_r double precision,
  ph01mcacl2_h double precision,
  freeiron_l text,
  freeiron_r text,
  freeiron_h text,
  feoxalate_l text,
  feoxalate_r text,
  feoxalate_h text,
  extracid_l double precision,
  extracid_r double precision,
  extracid_h double precision,
  extral_l float,
  extral_r float,
  extral_h float,
  aloxalate_l text,
  aloxalate_r text,
  aloxalate_h text,
  pbray1_l text,
  pbray1_r text,
  pbray1_h text,
  poxalate_l text,
  poxalate_r text,
  poxalate_h text,
  ph2osoluble_l text,
  ph2osoluble_r text,
  ph2osoluble_h text,
  ptotal_l text,
  ptotal_r text,
  ptotal_h text,
  excavdifcl text,
  excavdifms text,
  cokey integer,
  chkey integer
);
\COPY chorizon_copy FROM '/Users/michaelfelzan/Desktop/LCCMR_Soils/table_outputs/chorizon_copy.csv' WITH CSV Header ENCODING 'LATIN-1';
