DROP TABLE IF EXISTS muaggatt_copy;

CREATE TABLE muaggatt_copy
(
  OID_ int,
  musym text,
  muname text,
  mustatus text,
  slopegraddcp double precision,
  slopegradwta double precision,
  brockdepmin smallint,
  wtdepannmin smallint,
  wtdepaprjunmin smallint,
  flodfreqdcd text,
  flodfreqmax text,
  pondfreqprs smallint,
  aws025wta double precision,
  aws050wta double precision,
  aws0100wta double precision,
  aws0150wta double precision,
  drclassdcd text,
  drclasswettest text,
  hydgrpdcd text,
  iccdcd smallint,
  iccdcdpct smallint,
  niccdcd smallint,
  niccdcdpct smallint,
  engdwobdcd text,
  engdwbdcd text,
  engdwbll text,
  engdwbml text,
  engstafdcd text,
  engstafll text,
  engstafml text,
  engsldcd text,
  engsldcp text,
  englrsdcd text,
  engcmssdcd text,
  engcmssmp text,
  urbrecptdcd text,
  urbrecptwta double precision,
  forpehrtdcp text,
  hydclprs smallint,
  awmmfpwwta double precision,
  mukey integer
);
\COPY muaggatt_copy FROM '/Users/michaelfelzan/Desktop/LCCMR_Soils/table_outputs/muaggatt_copy.csv' WITH CSV Header ENCODING 'LATIN-1';
